version: "3.3"

services: 
  api:
    container_name: donkey
    restart: always
    build: .
    ports: 
      - "3001:3001"
    links:
      - db
    env_file:
       - src/.env
  db:
    container_name: postgresdb
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=postgres
    volumes:
         - pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
volumes: 
    pgdata: